# Denver Weather Preparation 2

In [356]:
import os.path
import datetime
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline

In [357]:
if not os.path.exists('../../data/prep/700_denWea.csv' ):
    print("Missing dataset file")

In [358]:
wea = pd.read_csv( '../../data/prep/700_denWea.csv', index_col="datetime", parse_dates=True)

In [359]:
wea.head()
wea.shape

(45252, 8)

In [360]:
cri = pd.read_csv ('../../data/prep/700_Denver.csv')

In [361]:
cri.head()

                  date Description         Lon        Lat
0  2013-01-02 00:37:00     assault -104.990480  39.728076
1  2013-01-02 15:00:00   vandalism -105.023305  39.758126
2  2013-01-02 15:00:00   vandalism -105.023305  39.758126
3  2013-01-02 15:00:00   vandalism -105.023305  39.758126
4  2013-01-02 15:00:00   vandalism -105.023305  39.758126

In [362]:
cri.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49853 entries, 0 to 49852
Data columns (total 4 columns):
date           49853 non-null object
Description    49853 non-null object
Lon            49853 non-null float64
Lat            49853 non-null float64
dtypes: float64(2), object(2)
memory usage: 1.5+ MB

In [363]:
cri['Date'] = pd.to_datetime(cri['date'])

In [364]:
cri.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49853 entries, 0 to 49852
Data columns (total 5 columns):
date           49853 non-null object
Description    49853 non-null object
Lon            49853 non-null float64
Lat            49853 non-null float64
Date           49853 non-null datetime64[ns]
dtypes: datetime64[ns](1), float64(2), object(2)
memory usage: 1.9+ MB

In [365]:
cri['Date'] = cri['Date'].dt.round('60min')

In [366]:
cri.head()

                  date Description         Lon        Lat                Date
0  2013-01-02 00:37:00     assault -104.990480  39.728076 2013-01-02 01:00:00
1  2013-01-02 15:00:00   vandalism -105.023305  39.758126 2013-01-02 15:00:00
2  2013-01-02 15:00:00   vandalism -105.023305  39.758126 2013-01-02 15:00:00
3  2013-01-02 15:00:00   vandalism -105.023305  39.758126 2013-01-02 15:00:00
4  2013-01-02 15:00:00   vandalism -105.023305  39.758126 2013-01-02 15:00:00

In [367]:
cri = cri.set_index('Date')

In [368]:
cri.head()

                                    date Description         Lon        Lat
Date
2013-01-02 01:00:00  2013-01-02 00:37:00     assault -104.990480  39.728076
2013-01-02 15:00:00  2013-01-02 15:00:00   vandalism -105.023305  39.758126
2013-01-02 15:00:00  2013-01-02 15:00:00   vandalism -105.023305  39.758126
2013-01-02 15:00:00  2013-01-02 15:00:00   vandalism -105.023305  39.758126
2013-01-02 15:00:00  2013-01-02 15:00:00   vandalism -105.023305  39.758126

In [369]:
cri = cri.drop(cri.columns[[0, 2, 3]], axis=1)

In [370]:
cri.head()
cri.shape

(49853, 1)

In [373]:
wea.head()

,Wind Speed,Description,Celcius,DescRate,TempRate,WindRate,Overall,Weather
datetime,,,,,,,,
2012-10-01 13:00:00,4.0,light rain,11.460000,0,2,2,4,Bad
2012-10-01 14:00:00,4.0,broken clouds,11.457306,2,2,2,6,Moderate
2012-10-01 15:00:00,3.0,broken clouds,11.449918,2,2,3,7,Moderate
2012-10-01 16:00:00,3.0,broken clouds,11.442530,2,2,3,7,Moderate
2012-10-01 17:00:00,3.0,broken clouds,11.435142,2,2,3,7,Moderate

### Joining the team dataframes

In [374]:
nba = pd.read_csv("../../data/prep/700_NBA.csv", index_col="Date", parse_dates=True)

In [375]:
nba.sort_index(ascending=True)

                            Visitor/Neutral            Home/Neutral
Date
2007-10-30 20:00:00         Houston Rockets      Los Angeles Lakers
2007-10-31 19:00:00      Philadelphia 76ers         Toronto Raptors
2007-10-31 20:00:00     Seattle SuperSonics          Denver Nuggets
2007-10-31 20:00:00           Chicago Bulls         New Jersey Nets
2007-11-02 19:00:00          Denver Nuggets  Minnesota Timberwolves
2007-11-02 20:00:00      Washington Wizards          Boston Celtics
2007-11-02 20:00:00      Philadelphia 76ers           Chicago Bulls
2007-11-02 20:00:00   Golden State Warriors    Los Angeles Clippers
2007-11-02 20:00:00      Los Angeles Lakers            Phoenix Suns
2007-11-03 19:00:00         New Jersey Nets      Philadelphia 76ers
2007-11-03 20:00:00           Chicago Bulls         Milwaukee Bucks
2007-11-04 12:00:00     Seattle SuperSonics    Los Angeles Clippers
2007-11-04 14:00:00          Boston Celtics         Toronto Raptors
2007-11-04 18:00:00     New Orleans Hornets          Denver Nuggets
2007-11-04 18:00:00               Utah Jazz      Los Angeles Lakers
2007-11-04 18:00:00  Minnesota Timberwolves         New York Knicks
2007-11-06 19:00:00           Orlando Magic  Minnesota Timberwolves
2007-11-06 20:00:00    Los Angeles Clippers           Chicago Bulls
2007-11-06 20:00:00     New Orleans Hornets      Los Angeles Lakers
2007-11-06 20:00:00          Denver Nuggets         New York Knicks
2007-11-07 19:00:00       Charlotte Bobcats      Philadelphia 76ers
2007-11-07 19:00:00    Los Angeles Clippers          Indiana Pacers
2007-11-07 20:00:00          Denver Nuggets          Boston Celtics
2007-11-08 19:00:00         Detroit Pistons           Chicago Bulls
2007-11-09 19:00:00         Toronto Raptors      Philadelphia 76ers
2007-11-09 20:00:00           Atlanta Hawks          Boston Celtics
2007-11-09 20:00:00    Los Angeles Clippers         Detroit Pistons
2007-11-09 20:00:00  Minnesota Timberwolves      Los Angeles Lakers
2007-11-09 20:00:00          Denver Nuggets      Washington Wizards
2007-11-10 19:00:00  Minnesota Timberwolves        Sacramento Kings
...                                     ...                     ...
2017-04-12 20:00:00  Minnesota Timberwolves         Houston Rockets
2017-04-12 20:00:00      Philadelphia 76ers         New York Knicks
2017-04-12 20:00:00          Denver Nuggets   Oklahoma City Thunder
2017-04-12 22:00:00      Los Angeles Lakers   Golden State Warriors
2017-04-12 22:00:00        Sacramento Kings    Los Angeles Clippers
2017-04-15 22:00:00               Utah Jazz    Los Angeles Clippers
2017-04-16 18:00:00           Chicago Bulls          Boston Celtics
2017-04-18 20:00:00           Chicago Bulls          Boston Celtics
2017-04-18 22:00:00               Utah Jazz    Los Angeles Clippers
2017-04-21 19:00:00          Boston Celtics           Chicago Bulls
2017-04-21 22:00:00    Los Angeles Clippers               Utah Jazz
2017-04-23 18:00:00          Boston Celtics           Chicago Bulls
2017-04-23 21:00:00    Los Angeles Clippers               Utah Jazz
2017-04-25 22:00:00               Utah Jazz    Los Angeles Clippers
2017-04-26 20:00:00           Chicago Bulls          Boston Celtics
2017-04-28 20:00:00          Boston Celtics           Chicago Bulls
2017-04-28 22:00:00    Los Angeles Clippers               Utah Jazz
2017-04-30 13:00:00      Washington Wizards          Boston Celtics
2017-04-30 16:00:00               Utah Jazz    Los Angeles Clippers
2017-05-02 20:00:00      Washington Wizards          Boston Celtics
2017-05-04 20:00:00          Boston Celtics      Washington Wizards
2017-05-07 18:00:00          Boston Celtics      Washington Wizards
2017-05-10 20:00:00      Washington Wizards          Boston Celtics
2017-05-12 20:00:00          Boston Celtics      Washington Wizards
2017-05-15 20:00:00      Washington Wizards          Boston Celtics
2017-05-17 20:00:00     Cleveland Cavaliers          Boston Celtics
2017-05-19 20:00:00     Cleveland Cavaliers          Boston Celtics
2017-05-21 20:00:00          Boston Celtics     Cleveland Cavaliers
2017-05-23 20:00:00          Boston Celtics     Cleveland Cavaliers
2017-05-25 20:00:00     Cleveland Cavaliers          Boston Celtics

[5354 rows x 2 columns]

In [376]:
bul = nba[(nba.values  == "Denver Nuggets")]

In [377]:
nfl = pd.read_csv("../../data/prep/800_NFL.csv", index_col="Date", parse_dates=True)
nfl.shape

(373, 2)

In [378]:
nfl.index.name = 'Date'

In [379]:
nfl.head()

           Home/Neutral Visitor/Neutral
Date
2007-09-09        Bills         Broncos
2007-09-09     Chargers           Bears
2007-09-09      Vikings         Falcons
2007-09-16        Bears          Chiefs
2007-09-16      Broncos         Raiders

In [380]:
nfl.sort_index(ascending=True)

                    Home/Neutral Visitor/Neutral
Date
2007-09-09 00:00:00        Bills         Broncos
2007-09-09 00:00:00     Chargers           Bears
2007-09-09 00:00:00      Vikings         Falcons
2007-09-16 00:00:00        Bears          Chiefs
2007-09-16 00:00:00      Broncos         Raiders
2007-09-16 00:00:00        Lions         Vikings
2007-09-23 00:00:00        Bears         Cowboys
2007-09-23 00:00:00      Broncos         Jaguars
2007-09-23 00:00:00       Chiefs         Vikings
2007-09-30 00:00:00        Colts         Broncos
2007-09-30 00:00:00        Lions           Bears
2007-09-30 00:00:00      Vikings         Packers
2007-10-07 00:00:00      Broncos        Chargers
2007-10-07 00:00:00      Packers           Bears
2007-10-14 00:00:00        Bears         Vikings
2007-10-21 00:00:00      Broncos        Steelers
2007-10-21 00:00:00      Cowboys         Vikings
2007-10-21 00:00:00       Eagles           Bears
2007-10-28 00:00:00        Bears           Lions
2007-10-28 00:00:00      Vikings          Eagles
2007-10-29 00:00:00      Broncos         Packers
2007-11-04 00:00:00        Lions         Broncos
2007-11-04 00:00:00      Vikings        Chargers
2007-11-11 00:00:00       Chiefs         Broncos
2007-11-11 00:00:00      Packers         Vikings
2007-11-11 00:00:00      Raiders           Bears
2007-11-18 00:00:00     Seahawks           Bears
2007-11-18 00:00:00      Vikings         Raiders
2007-11-19 00:00:00      Broncos          Titans
2007-11-25 00:00:00        Bears         Broncos
...                          ...             ...
2014-10-19 17:00:00        Bears        Dolphins
2014-10-19 17:00:00        Bills         Vikings
2014-10-20 00:00:00      Broncos           49ers
2014-10-24 00:00:00      Broncos        Chargers
2014-10-26 17:00:00   Buccaneers         Vikings
2014-10-26 17:00:00     Patriots           Bears
2014-11-02 17:00:00      Vikings        Redskins
2014-11-02 20:00:00     Patriots         Broncos
2014-11-09 21:00:00      Raiders         Broncos
2014-11-10 02:00:00      Packers           Bears
2014-11-16 18:00:00        Bears         Vikings
2014-11-16 18:00:00         Rams         Broncos
2014-11-23 18:00:00        Bears      Buccaneers
2014-11-23 18:00:00      Vikings         Packers
2014-11-23 21:00:00      Broncos        Dolphins
2014-11-28 06:00:00        Lions           Bears
2014-11-30 18:00:00      Vikings        Panthers
2014-12-01 02:00:00       Chiefs         Broncos
2014-12-05 01:00:00        Bears         Cowboys
2014-12-07 18:00:00      Vikings            Jets
2014-12-07 21:00:00      Broncos           Bills
2014-12-14 18:00:00        Lions         Vikings
2014-12-14 21:00:00     Chargers         Broncos
2014-12-16 02:00:00        Bears          Saints
2014-12-21 18:00:00        Bears           Lions
2014-12-21 18:00:00     Dolphins         Vikings
2014-12-23 02:00:00      Bengals         Broncos
2014-12-28 18:00:00      Vikings           Bears
2014-12-28 21:00:00      Broncos         Raiders
2015-01-11 22:00:00      Broncos           Colts

[373 rows x 2 columns]

In [381]:
bea = nfl[(nfl.values  == "Broncos")]

In [382]:
bea.head()

           Home/Neutral Visitor/Neutral
Date
2007-09-09        Bills         Broncos
2007-09-16      Broncos         Raiders
2007-09-23      Broncos         Jaguars
2007-09-30        Colts         Broncos
2007-10-07      Broncos        Chargers

In [383]:
fram1 = [bea, bul]
df = pd.concat(fram1)

In [384]:
df.head()

           Home/Neutral Visitor/Neutral
Date
2007-09-09        Bills         Broncos
2007-09-16      Broncos         Raiders
2007-09-23      Broncos         Jaguars
2007-09-30        Colts         Broncos
2007-10-07      Broncos        Chargers

In [385]:
df = df.sort_index(ascending=True)

In [386]:
conditions = [
    (df['Home/Neutral'] == 'Denver Nuggets') | (df['Visitor/Neutral'] == 'Denver Nuggets'),
    (df['Home/Neutral'] == 'Broncos') | (df['Visitor/Neutral'] == 'Broncos') ]
choices = ['NBA', 'NFL']
df['Game'] = np.select(conditions, choices, default='error')

In [387]:
df

                               Home/Neutral         Visitor/Neutral Game
Date
2007-09-09 00:00:00                   Bills                 Broncos  NFL
2007-09-16 00:00:00                 Broncos                 Raiders  NFL
2007-09-23 00:00:00                 Broncos                 Jaguars  NFL
2007-09-30 00:00:00                   Colts                 Broncos  NFL
2007-10-07 00:00:00                 Broncos                Chargers  NFL
2007-10-21 00:00:00                 Broncos                Steelers  NFL
2007-10-29 00:00:00                 Broncos                 Packers  NFL
2007-10-31 20:00:00          Denver Nuggets     Seattle SuperSonics  NBA
2007-11-02 19:00:00  Minnesota Timberwolves          Denver Nuggets  NBA
2007-11-04 00:00:00                   Lions                 Broncos  NFL
2007-11-04 18:00:00          Denver Nuggets     New Orleans Hornets  NBA
2007-11-06 20:00:00         New York Knicks          Denver Nuggets  NBA
2007-11-07 20:00:00          Boston Celtics          Denver Nuggets  NBA
2007-11-09 20:00:00      Washington Wizards          Denver Nuggets  NBA
2007-11-10 19:00:00          Indiana Pacers          Denver Nuggets  NBA
2007-11-11 00:00:00                  Chiefs                 Broncos  NFL
2007-11-12 19:00:00          Denver Nuggets     Cleveland Cavaliers  NBA
2007-11-14 19:00:00          Denver Nuggets  Portland Trail Blazers  NBA
2007-11-17 19:00:00          Denver Nuggets         New York Knicks  NBA
2007-11-19 00:00:00                 Broncos                  Titans  NFL
2007-11-20 19:00:00          Denver Nuggets           Chicago Bulls  NBA
2007-11-21 20:00:00    Los Angeles Clippers          Denver Nuggets  NBA
2007-11-23 19:00:00          Denver Nuggets  Minnesota Timberwolves  NBA
2007-11-24 20:00:00         Houston Rockets          Denver Nuggets  NBA
2007-11-25 00:00:00                   Bears                 Broncos  NFL
2007-11-27 19:00:00          Denver Nuggets          Indiana Pacers  NBA
2007-11-29 20:00:00      Los Angeles Lakers          Denver Nuggets  NBA
2007-11-30 20:00:00          Denver Nuggets    Los Angeles Clippers  NBA
2007-12-02 00:00:00                 Raiders                 Broncos  NFL
2007-12-02 18:00:00          Denver Nuggets              Miami Heat  NBA
...                                     ...                     ...  ...
2017-02-10 20:00:00         New York Knicks          Denver Nuggets  NBA
2017-02-11 20:00:00     Cleveland Cavaliers          Denver Nuggets  NBA
2017-02-13 21:00:00          Denver Nuggets   Golden State Warriors  NBA
2017-02-15 21:00:00          Denver Nuggets  Minnesota Timberwolves  NBA
2017-02-23 22:00:00        Sacramento Kings          Denver Nuggets  NBA
2017-02-24 21:00:00          Denver Nuggets           Brooklyn Nets  NBA
2017-02-26 17:00:00          Denver Nuggets       Memphis Grizzlies  NBA
2017-02-28 20:00:00           Chicago Bulls          Denver Nuggets  NBA
2017-03-01 20:00:00         Milwaukee Bucks          Denver Nuggets  NBA
2017-03-04 21:00:00          Denver Nuggets       Charlotte Hornets  NBA
2017-03-06 21:00:00          Denver Nuggets        Sacramento Kings  NBA
2017-03-08 21:00:00          Denver Nuggets      Washington Wizards  NBA
2017-03-10 21:00:00          Denver Nuggets          Boston Celtics  NBA
2017-03-11 22:00:00        Sacramento Kings          Denver Nuggets  NBA
2017-03-13 22:00:00          Denver Nuggets      Los Angeles Lakers  NBA
2017-03-16 21:00:00          Denver Nuggets    Los Angeles Clippers  NBA
2017-03-18 22:00:00          Denver Nuggets         Houston Rockets  NBA
2017-03-20 20:00:00         Houston Rockets          Denver Nuggets  NBA
2017-03-22 21:00:00          Denver Nuggets     Cleveland Cavaliers  NBA
2017-03-24 19:00:00          Indiana Pacers          Denver Nuggets  NBA
2017-03-26 20:00:00          Denver Nuggets    New Orleans Pelicans  NBA
2017-03-28 22:00:00  Portland Trail Blazers          Denver Nuggets  NBA
2017-03-31 19:00:00       Charlotte Hornets          Denver Nuggets  NBA
2017-04-02 18:00:00              Miami Heat          Denver Nuggets  NBA
2017-04-04 20:00:00    New Orleans Pelicans          Denver Nuggets  NBA
2017-04-05 20:00:00         Houston Rockets          Denver Nuggets  NBA
2017-04-07 21:00:00          Denver Nuggets    New Orleans Pelicans  NBA
2017-04-09 17:00:00          Denver Nuggets   Oklahoma City Thunder  NBA
2017-04-11 20:00:00        Dallas Mavericks          Denver Nuggets  NBA
2017-04-12 20:00:00   Oklahoma City Thunder          Denver Nuggets  NBA

[969 rows x 3 columns]

In [388]:
df = df.drop(df.columns[[0, 1]], axis=1)

In [389]:
df.head()

           Game
Date
2007-09-09  NFL
2007-09-16  NFL
2007-09-23  NFL
2007-09-30  NFL
2007-10-07  NFL

### Merging with the Weather

In [390]:
comp = pd.merge(wea,df,how="left",right_index=True,left_index=True)
comp

,Wind Speed,Description,Celcius,DescRate,TempRate,WindRate,Overall,Weather,Game
2012-10-01 13:00:00,4.0,light rain,11.460000,0,2,2,4,Bad,NaN
2012-10-01 14:00:00,4.0,broken clouds,11.457306,2,2,2,6,Moderate,NaN
2012-10-01 15:00:00,3.0,broken clouds,11.449918,2,2,3,7,Moderate,NaN
2012-10-01 16:00:00,3.0,broken clouds,11.442530,2,2,3,7,Moderate,NaN
2012-10-01 17:00:00,3.0,broken clouds,11.435142,2,2,3,7,Moderate,NaN
2012-10-01 18:00:00,3.0,broken clouds,11.427755,2,2,3,7,Moderate,NaN
2012-10-01 19:00:00,3.0,broken clouds,11.420367,2,2,3,7,Moderate,NaN
2012-10-01 20:00:00,3.0,broken clouds,11.412979,2,2,3,7,Moderate,NaN
2012-10-01 21:00:00,3.0,broken clouds,11.405591,2,2,3,7,Moderate,NaN
2012-10-01 22:00:00,3.0,broken clouds,11.398204,2,2,3,7,Moderate,NaN
2012-10-01 23:00:00,3.0,broken clouds,11.390816,2,2,3,7,Moderate,NaN
2012-10-02 00:00:00,3.0,broken clouds,11.383428,2,2,3,7,Moderate,NaN
2012-10-02 01:00:00,3.0,broken clouds,11.376040,2,2,3,7,Moderate,NaN
2012-10-02 02:00:00,3.0,broken clouds,11.368653,2,2,3,7,Moderate,NaN
2012-10-02 03:00:00,3.0,broken clouds,11.361265,2,2,3,7,Moderate,NaN
2012-10-02 04:00:00,2.0,broken clouds,11.353877,2,2,3,7,Moderate,NaN
2012-10-02 05:00:00,2.0,broken clouds,11.346490,2,2,3,7,Moderate,NaN
2012-10-02 06:00:00,2.0,broken clouds,11.339102,2,2,3,7,Moderate,NaN
2012-10-02 07:00:00,2.0,broken clouds,11.331714,2,2,3,7,Moderate,NaN
2012-10-02 08:00:00,2.0,broken clouds,11.324326,2,2,3,7,Moderate,NaN
2012-10-02 09:00:00,2.0,broken clouds,11.316939,2,2,3,7,Moderate,NaN
2012-10-02 10:00:00,2.0,broken clouds,11.309551,2,2,3,7,Moderate,NaN
2012-10-02 11:00:00,2.0,broken clouds,11.302163,2,2,3,7,Moderate,NaN
2012-10-02 12:00:00,2.0,broken clouds,11.294775,2,2,3,7,Moderate,NaN
2012-10-02 13:00:00,2.0,broken clouds,11.287388,2,2,3,7,Moderate,NaN
2012-10-02 14:00:00,2.0,light rain,11.280000,0,2,3,5,Bad,NaN
2012-10-02 15:00:00,2.0,proximity shower rain,12.160000,0,2,3,5,Bad,NaN
2012-10-02 16:00:00,0.0,sky is clear,13.300000,3,2,3,8,Good,NaN
2012-10-02 17:00:00,0.0,sky is clear,14.690000,3,2,3,8,Good,NaN
2012-10-02 18:00:00,4.0,scattered clouds,16.030000,3,2,2,7,Moderate,NaN
...,...,...,...,...,...,...,...,...,...
2017-11-28 19:00:00,3.0,haze,4.870000,2,0,3,5,Bad,NaN
2017-11-28 20:00:00,2.0,sky is clear,5.400000,3,0,3,6,Moderate,NaN
2017-11-28 21:00:00,1.0,scattered clouds,6.490000,3,0,3,6,Moderate,NaN
2017-11-28 22:00:00,3.0,sky is clear,7.000000,3,0,3,6,Moderate,NaN
2017-11-28 23:00:00,3.0,sky is clear,3.930000,3,0,3,6,Moderate,NaN
2017-11-29 00:00:00,1.0,haze,5.890000,2,0,3,5,Bad,NaN
2017-11-29 01:00:00,1.0,sky is clear,3.110000,3,0,3,6,Moderate,NaN
2017-11-29 02:00:00,2.0,sky is clear,1.110000,3,0,3,6,Moderate,NaN
2017-11-29 03:00:00,2.0,sky is clear,0.560000,3,0,3,6,Moderate,NaN
2017-11-29 04:00:00,1.0,sky is clear,0.450000,3,0,3,6,Moderate,NaN
2017-11-29 05:00:00,1.0,sky is clear,0.440000,3,0,3,6,Moderate,NaN
2017-11-29 06:00:00,2.0,sky is clear,0.100000,3,0,3,6,Moderate,NaN
2017-11-29 07:00:00,2.0,sky is clear,-0.090000,3,0,3,6,Moderate,NaN
2017-11-29 08:00:00,1.0,mist,-0.280000,0,0,3,3,Bad,NaN
2017-11-29 09:00:00,1.0,sky is clear,-0.390000,3,0,3,6,Moderate,NaN
2017-11-29 10:00:00,1.0,sky is clear,-1.190000,3,0,3,6,Moderate,NaN
2017-11-29 11:00:00,2.0,sky is clear,-1.590000,3,0,3,6,Moderate,NaN
2017-11-29 12:00:00,2.0,sky is clear,-1.590000,3,0,3,6,Moderate,NaN
2017-11-29 13:00:00,2.0,sky is clear,-1.090000,3,0,3,6,Moderate,NaN
2017-11-29 14:00:00,7.0,broken clouds,0.220000,2,0,2,4,Bad,NaN
2017-11-29 15:00:00,2.0,broken clouds,0.620000,2,0,3,5,Bad,NaN
2017-11-29 16:00:00,2.0,sky is clear,1.920000,3,0,3,6,Moderate,NaN
2017-11-29 17:00:00,1.0,sky is clear,3.610000,3,0,3,6,Moderate,NaN
2017-11-29 18:00:00,3.0,sky is clear,10.010000,3,2,3,8,Good,NaN
2017-11-29 19:00:00,4.0,sky is clear,13.570000,3,2,2,7,Moderate,NaN
2017-11-29 20:00:00,3.0,broken clouds,16.410000,2,2,3,7,Moderate,NaN
2017-11-29 21:00:00,6.0,sky is clear,17.550000,3,2,2,7,Moderate,NaN
2017-11-29 22:00:00,3.0,sky is clear,16.560000,3,2,3,8,Good,NaN
2017-11-29 23:00:00,1.0,haze,16.020000,2,2,3,7,Moderate,NaN
2017-11-30 00:00:00,3.0,sky is clear,12.030000,3,2,3,8,Good,NaN

In [391]:
comp.index.duplicated()

array([False, False, False, ..., False, False, False], dtype=bool)

In [392]:
comp = comp[~comp.index.duplicated(keep='first')]

In [393]:
comp

,Wind Speed,Description,Celcius,DescRate,TempRate,WindRate,Overall,Weather,Game
2012-10-01 13:00:00,4.0,light rain,11.460000,0,2,2,4,Bad,NaN
2012-10-01 14:00:00,4.0,broken clouds,11.457306,2,2,2,6,Moderate,NaN
2012-10-01 15:00:00,3.0,broken clouds,11.449918,2,2,3,7,Moderate,NaN
2012-10-01 16:00:00,3.0,broken clouds,11.442530,2,2,3,7,Moderate,NaN
2012-10-01 17:00:00,3.0,broken clouds,11.435142,2,2,3,7,Moderate,NaN
2012-10-01 18:00:00,3.0,broken clouds,11.427755,2,2,3,7,Moderate,NaN
2012-10-01 19:00:00,3.0,broken clouds,11.420367,2,2,3,7,Moderate,NaN
2012-10-01 20:00:00,3.0,broken clouds,11.412979,2,2,3,7,Moderate,NaN
2012-10-01 21:00:00,3.0,broken clouds,11.405591,2,2,3,7,Moderate,NaN
2012-10-01 22:00:00,3.0,broken clouds,11.398204,2,2,3,7,Moderate,NaN
2012-10-01 23:00:00,3.0,broken clouds,11.390816,2,2,3,7,Moderate,NaN
2012-10-02 00:00:00,3.0,broken clouds,11.383428,2,2,3,7,Moderate,NaN
2012-10-02 01:00:00,3.0,broken clouds,11.376040,2,2,3,7,Moderate,NaN
2012-10-02 02:00:00,3.0,broken clouds,11.368653,2,2,3,7,Moderate,NaN
2012-10-02 03:00:00,3.0,broken clouds,11.361265,2,2,3,7,Moderate,NaN
2012-10-02 04:00:00,2.0,broken clouds,11.353877,2,2,3,7,Moderate,NaN
2012-10-02 05:00:00,2.0,broken clouds,11.346490,2,2,3,7,Moderate,NaN
2012-10-02 06:00:00,2.0,broken clouds,11.339102,2,2,3,7,Moderate,NaN
2012-10-02 07:00:00,2.0,broken clouds,11.331714,2,2,3,7,Moderate,NaN
2012-10-02 08:00:00,2.0,broken clouds,11.324326,2,2,3,7,Moderate,NaN
2012-10-02 09:00:00,2.0,broken clouds,11.316939,2,2,3,7,Moderate,NaN
2012-10-02 10:00:00,2.0,broken clouds,11.309551,2,2,3,7,Moderate,NaN
2012-10-02 11:00:00,2.0,broken clouds,11.302163,2,2,3,7,Moderate,NaN
2012-10-02 12:00:00,2.0,broken clouds,11.294775,2,2,3,7,Moderate,NaN
2012-10-02 13:00:00,2.0,broken clouds,11.287388,2,2,3,7,Moderate,NaN
2012-10-02 14:00:00,2.0,light rain,11.280000,0,2,3,5,Bad,NaN
2012-10-02 15:00:00,2.0,proximity shower rain,12.160000,0,2,3,5,Bad,NaN
2012-10-02 16:00:00,0.0,sky is clear,13.300000,3,2,3,8,Good,NaN
2012-10-02 17:00:00,0.0,sky is clear,14.690000,3,2,3,8,Good,NaN
2012-10-02 18:00:00,4.0,scattered clouds,16.030000,3,2,2,7,Moderate,NaN
...,...,...,...,...,...,...,...,...,...
2017-11-28 19:00:00,3.0,haze,4.870000,2,0,3,5,Bad,NaN
2017-11-28 20:00:00,2.0,sky is clear,5.400000,3,0,3,6,Moderate,NaN
2017-11-28 21:00:00,1.0,scattered clouds,6.490000,3,0,3,6,Moderate,NaN
2017-11-28 22:00:00,3.0,sky is clear,7.000000,3,0,3,6,Moderate,NaN
2017-11-28 23:00:00,3.0,sky is clear,3.930000,3,0,3,6,Moderate,NaN
2017-11-29 00:00:00,1.0,haze,5.890000,2,0,3,5,Bad,NaN
2017-11-29 01:00:00,1.0,sky is clear,3.110000,3,0,3,6,Moderate,NaN
2017-11-29 02:00:00,2.0,sky is clear,1.110000,3,0,3,6,Moderate,NaN
2017-11-29 03:00:00,2.0,sky is clear,0.560000,3,0,3,6,Moderate,NaN
2017-11-29 04:00:00,1.0,sky is clear,0.450000,3,0,3,6,Moderate,NaN
2017-11-29 05:00:00,1.0,sky is clear,0.440000,3,0,3,6,Moderate,NaN
2017-11-29 06:00:00,2.0,sky is clear,0.100000,3,0,3,6,Moderate,NaN
2017-11-29 07:00:00,2.0,sky is clear,-0.090000,3,0,3,6,Moderate,NaN
2017-11-29 08:00:00,1.0,mist,-0.280000,0,0,3,3,Bad,NaN
2017-11-29 09:00:00,1.0,sky is clear,-0.390000,3,0,3,6,Moderate,NaN
2017-11-29 10:00:00,1.0,sky is clear,-1.190000,3,0,3,6,Moderate,NaN
2017-11-29 11:00:00,2.0,sky is clear,-1.590000,3,0,3,6,Moderate,NaN
2017-11-29 12:00:00,2.0,sky is clear,-1.590000,3,0,3,6,Moderate,NaN
2017-11-29 13:00:00,2.0,sky is clear,-1.090000,3,0,3,6,Moderate,NaN
2017-11-29 14:00:00,7.0,broken clouds,0.220000,2,0,2,4,Bad,NaN
2017-11-29 15:00:00,2.0,broken clouds,0.620000,2,0,3,5,Bad,NaN
2017-11-29 16:00:00,2.0,sky is clear,1.920000,3,0,3,6,Moderate,NaN
2017-11-29 17:00:00,1.0,sky is clear,3.610000,3,0,3,6,Moderate,NaN
2017-11-29 18:00:00,3.0,sky is clear,10.010000,3,2,3,8,Good,NaN
2017-11-29 19:00:00,4.0,sky is clear,13.570000,3,2,2,7,Moderate,NaN
2017-11-29 20:00:00,3.0,broken clouds,16.410000,2,2,3,7,Moderate,NaN
2017-11-29 21:00:00,6.0,sky is clear,17.550000,3,2,2,7,Moderate,NaN
2017-11-29 22:00:00,3.0,sky is clear,16.560000,3,2,3,8,Good,NaN
2017-11-29 23:00:00,1.0,haze,16.020000,2,2,3,7,Moderate,NaN
2017-11-30 00:00:00,3.0,sky is clear,12.030000,3,2,3,8,Good,NaN

In [394]:
comp['Game Day'] = comp.groupby("Weather")["Game"].ffill(limit=5)

C:\Users\Cathal Mc Connell\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [395]:
comp.head()

,Wind Speed,Description,Celcius,DescRate,TempRate,WindRate,Overall,Weather,Game,Game Day
2012-10-01 13:00:00,4.0,light rain,11.460000,0,2,2,4,Bad,NaN,NaN
2012-10-01 14:00:00,4.0,broken clouds,11.457306,2,2,2,6,Moderate,NaN,NaN
2012-10-01 15:00:00,3.0,broken clouds,11.449918,2,2,3,7,Moderate,NaN,NaN
2012-10-01 16:00:00,3.0,broken clouds,11.442530,2,2,3,7,Moderate,NaN,NaN
2012-10-01 17:00:00,3.0,broken clouds,11.435142,2,2,3,7,Moderate,NaN,NaN

In [396]:
comp['Game Day'] = comp.groupby("Weather")["Game Day"].bfill(limit=2)

C:\Users\Cathal Mc Connell\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [397]:
comp['Domestic'] = comp.groupby("Weather")["Game"].ffill(limit=7)

C:\Users\Cathal Mc Connell\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [398]:
comp

,Wind Speed,Description,Celcius,DescRate,TempRate,WindRate,Overall,Weather,Game,Game Day,Domestic
2012-10-01 13:00:00,4.0,light rain,11.460000,0,2,2,4,Bad,NaN,NaN,NaN
2012-10-01 14:00:00,4.0,broken clouds,11.457306,2,2,2,6,Moderate,NaN,NaN,NaN
2012-10-01 15:00:00,3.0,broken clouds,11.449918,2,2,3,7,Moderate,NaN,NaN,NaN
2012-10-01 16:00:00,3.0,broken clouds,11.442530,2,2,3,7,Moderate,NaN,NaN,NaN
2012-10-01 17:00:00,3.0,broken clouds,11.435142,2,2,3,7,Moderate,NaN,NaN,NaN
2012-10-01 18:00:00,3.0,broken clouds,11.427755,2,2,3,7,Moderate,NaN,NaN,NaN
2012-10-01 19:00:00,3.0,broken clouds,11.420367,2,2,3,7,Moderate,NaN,NaN,NaN
2012-10-01 20:00:00,3.0,broken clouds,11.412979,2,2,3,7,Moderate,NaN,NaN,NaN
2012-10-01 21:00:00,3.0,broken clouds,11.405591,2,2,3,7,Moderate,NaN,NaN,NaN
2012-10-01 22:00:00,3.0,broken clouds,11.398204,2,2,3,7,Moderate,NaN,NaN,NaN
2012-10-01 23:00:00,3.0,broken clouds,11.390816,2,2,3,7,Moderate,NaN,NaN,NaN
2012-10-02 00:00:00,3.0,broken clouds,11.383428,2,2,3,7,Moderate,NaN,NaN,NaN
2012-10-02 01:00:00,3.0,broken clouds,11.376040,2,2,3,7,Moderate,NaN,NaN,NaN
2012-10-02 02:00:00,3.0,broken clouds,11.368653,2,2,3,7,Moderate,NaN,NaN,NaN
2012-10-02 03:00:00,3.0,broken clouds,11.361265,2,2,3,7,Moderate,NaN,NaN,NaN
2012-10-02 04:00:00,2.0,broken clouds,11.353877,2,2,3,7,Moderate,NaN,NaN,NaN
2012-10-02 05:00:00,2.0,broken clouds,11.346490,2,2,3,7,Moderate,NaN,NaN,NaN
2012-10-02 06:00:00,2.0,broken clouds,11.339102,2,2,3,7,Moderate,NaN,NaN,NaN
2012-10-02 07:00:00,2.0,broken clouds,11.331714,2,2,3,7,Moderate,NaN,NaN,NaN
2012-10-02 08:00:00,2.0,broken clouds,11.324326,2,2,3,7,Moderate,NaN,NaN,NaN
2012-10-02 09:00:00,2.0,broken clouds,11.316939,2,2,3,7,Moderate,NaN,NaN,NaN
2012-10-02 10:00:00,2.0,broken clouds,11.309551,2,2,3,7,Moderate,NaN,NaN,NaN
2012-10-02 11:00:00,2.0,broken clouds,11.302163,2,2,3,7,Moderate,NaN,NaN,NaN
2012-10-02 12:00:00,2.0,broken clouds,11.294775,2,2,3,7,Moderate,NaN,NaN,NaN
2012-10-02 13:00:00,2.0,broken clouds,11.287388,2,2,3,7,Moderate,NaN,NaN,NaN
2012-10-02 14:00:00,2.0,light rain,11.280000,0,2,3,5,Bad,NaN,NaN,NaN
2012-10-02 15:00:00,2.0,proximity shower rain,12.160000,0,2,3,5,Bad,NaN,NaN,NaN
2012-10-02 16:00:00,0.0,sky is clear,13.300000,3,2,3,8,Good,NaN,NaN,NaN
2012-10-02 17:00:00,0.0,sky is clear,14.690000,3,2,3,8,Good,NaN,NaN,NaN
2012-10-02 18:00:00,4.0,scattered clouds,16.030000,3,2,2,7,Moderate,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2017-11-28 19:00:00,3.0,haze,4.870000,2,0,3,5,Bad,NaN,NaN,NaN
2017-11-28 20:00:00,2.0,sky is clear,5.400000,3,0,3,6,Moderate,NaN,NaN,NaN
2017-11-28 21:00:00,1.0,scattered clouds,6.490000,3,0,3,6,Moderate,NaN,NaN,NaN
2017-11-28 22:00:00,3.0,sky is clear,7.000000,3,0,3,6,Moderate,NaN,NaN,NaN
2017-11-28 23:00:00,3.0,sky is clear,3.930000,3,0,3,6,Moderate,NaN,NaN,NaN
2017-11-29 00:00:00,1.0,haze,5.890000,2,0,3,5,Bad,NaN,NaN,NaN
2017-11-29 01:00:00,1.0,sky is clear,3.110000,3,0,3,6,Moderate,NaN,NaN,NaN
2017-11-29 02:00:00,2.0,sky is clear,1.110000,3,0,3,6,Moderate,NaN,NaN,NaN
2017-11-29 03:00:00,2.0,sky is clear,0.560000,3,0,3,6,Moderate,NaN,NaN,NaN
2017-11-29 04:00:00,1.0,sky is clear,0.450000,3,0,3,6,Moderate,NaN,NaN,NaN
2017-11-29 05:00:00,1.0,sky is clear,0.440000,3,0,3,6,Moderate,NaN,NaN,NaN
2017-11-29 06:00:00,2.0,sky is clear,0.100000,3,0,3,6,Moderate,NaN,NaN,NaN
2017-11-29 07:00:00,2.0,sky is clear,-0.090000,3,0,3,6,Moderate,NaN,NaN,NaN
2017-11-29 08:00:00,1.0,mist,-0.280000,0,0,3,3,Bad,NaN,NaN,NaN
2017-11-29 09:00:00,1.0,sky is clear,-0.390000,3,0,3,6,Moderate,NaN,NaN,NaN
2017-11-29 10:00:00,1.0,sky is clear,-1.190000,3,0,3,6,Moderate,NaN,NaN,NaN
2017-11-29 11:00:00,2.0,sky is clear,-1.590000,3,0,3,6,Moderate,NaN,NaN,NaN
2017-11-29 12:00:00,2.0,sky is clear,-1.590000,3,0,3,6,Moderate,NaN,NaN,NaN
2017-11-29 13:00:00,2.0,sky is clear,-1.090000,3,0,3,6,Moderate,NaN,NaN,NaN
2017-11-29 14:00:00,7.0,broken clouds,0.220000,2,0,2,4,Bad,NaN,NaN,NaN
2017-11-29 15:00:00,2.0,broken clouds,0.620000,2,0,3,5,Bad,NaN,NaN,NaN
2017-11-29 16:00:00,2.0,sky is clear,1.920000,3,0,3,6,Moderate,NaN,NaN,NaN
2017-11-29 17:00:00,1.0,sky is clear,3.610000,3,0,3,6,Moderate,NaN,NaN,NaN
2017-11-29 18:00:00,3.0,sky is clear,10.010000,3,2,3,8,Good,NaN,NaN,NaN
2017-11-29 19:00:00,4.0,sky is clear,13.570000,3,2,2,7,Moderate,NaN,NaN,NaN
2017-11-29 20:00:00,3.0,broken clouds,16.410000,2,2,3,7,Moderate,NaN,NaN,NaN
2017-11-29 21:00:00,6.0,sky is clear,17.550000,3,2,2,7,Moderate,NaN,NaN,NaN
2017-11-29 22:00:00,3.0,sky is clear,16.560000,3,2,3,8,Good,NaN,NaN,NaN
2017-11-29 23:00:00,1.0,haze,16.020000,2,2,3,7,Moderate,NaN,NaN,NaN
2017-11-30 00:00:00,3.0,sky is clear,12.030000,3,2,3,8,Good,NaN,NaN,NaN

### Merging with the Crime

In [399]:
test = pd.merge(comp,cri,how="left",right_index=True,left_index=True)
test

,Wind Speed,Description_x,Celcius,DescRate,TempRate,WindRate,Overall,Weather,Game,Game Day,Domestic,Description_y
2012-10-01 13:00:00,4.0,light rain,11.460000,0,2,2,4,Bad,NaN,NaN,NaN,NaN
2012-10-01 14:00:00,4.0,broken clouds,11.457306,2,2,2,6,Moderate,NaN,NaN,NaN,NaN
2012-10-01 15:00:00,3.0,broken clouds,11.449918,2,2,3,7,Moderate,NaN,NaN,NaN,NaN
2012-10-01 16:00:00,3.0,broken clouds,11.442530,2,2,3,7,Moderate,NaN,NaN,NaN,NaN
2012-10-01 17:00:00,3.0,broken clouds,11.435142,2,2,3,7,Moderate,NaN,NaN,NaN,NaN
2012-10-01 18:00:00,3.0,broken clouds,11.427755,2,2,3,7,Moderate,NaN,NaN,NaN,NaN
2012-10-01 19:00:00,3.0,broken clouds,11.420367,2,2,3,7,Moderate,NaN,NaN,NaN,NaN
2012-10-01 20:00:00,3.0,broken clouds,11.412979,2,2,3,7,Moderate,NaN,NaN,NaN,NaN
2012-10-01 21:00:00,3.0,broken clouds,11.405591,2,2,3,7,Moderate,NaN,NaN,NaN,NaN
2012-10-01 22:00:00,3.0,broken clouds,11.398204,2,2,3,7,Moderate,NaN,NaN,NaN,NaN
2012-10-01 23:00:00,3.0,broken clouds,11.390816,2,2,3,7,Moderate,NaN,NaN,NaN,NaN
2012-10-02 00:00:00,3.0,broken clouds,11.383428,2,2,3,7,Moderate,NaN,NaN,NaN,NaN
2012-10-02 01:00:00,3.0,broken clouds,11.376040,2,2,3,7,Moderate,NaN,NaN,NaN,NaN
2012-10-02 02:00:00,3.0,broken clouds,11.368653,2,2,3,7,Moderate,NaN,NaN,NaN,NaN
2012-10-02 03:00:00,3.0,broken clouds,11.361265,2,2,3,7,Moderate,NaN,NaN,NaN,NaN
2012-10-02 04:00:00,2.0,broken clouds,11.353877,2,2,3,7,Moderate,NaN,NaN,NaN,NaN
2012-10-02 05:00:00,2.0,broken clouds,11.346490,2,2,3,7,Moderate,NaN,NaN,NaN,NaN
2012-10-02 06:00:00,2.0,broken clouds,11.339102,2,2,3,7,Moderate,NaN,NaN,NaN,NaN
2012-10-02 07:00:00,2.0,broken clouds,11.331714,2,2,3,7,Moderate,NaN,NaN,NaN,NaN
2012-10-02 08:00:00,2.0,broken clouds,11.324326,2,2,3,7,Moderate,NaN,NaN,NaN,NaN
2012-10-02 09:00:00,2.0,broken clouds,11.316939,2,2,3,7,Moderate,NaN,NaN,NaN,NaN
2012-10-02 10:00:00,2.0,broken clouds,11.309551,2,2,3,7,Moderate,NaN,NaN,NaN,NaN
2012-10-02 11:00:00,2.0,broken clouds,11.302163,2,2,3,7,Moderate,NaN,NaN,NaN,NaN
2012-10-02 12:00:00,2.0,broken clouds,11.294775,2,2,3,7,Moderate,NaN,NaN,NaN,NaN
2012-10-02 13:00:00,2.0,broken clouds,11.287388,2,2,3,7,Moderate,NaN,NaN,NaN,NaN
2012-10-02 14:00:00,2.0,light rain,11.280000,0,2,3,5,Bad,NaN,NaN,NaN,NaN
2012-10-02 15:00:00,2.0,proximity shower rain,12.160000,0,2,3,5,Bad,NaN,NaN,NaN,NaN
2012-10-02 16:00:00,0.0,sky is clear,13.300000,3,2,3,8,Good,NaN,NaN,NaN,NaN
2012-10-02 17:00:00,0.0,sky is clear,14.690000,3,2,3,8,Good,NaN,NaN,NaN,NaN
2012-10-02 18:00:00,4.0,scattered clouds,16.030000,3,2,2,7,Moderate,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
2017-11-29 04:00:00,1.0,sky is clear,0.450000,3,0,3,6,Moderate,NaN,NaN,NaN,domestic
2017-11-29 05:00:00,1.0,sky is clear,0.440000,3,0,3,6,Moderate,NaN,NaN,NaN,NaN
2017-11-29 06:00:00,2.0,sky is clear,0.100000,3,0,3,6,Moderate,NaN,NaN,NaN,NaN
2017-11-29 07:00:00,2.0,sky is clear,-0.090000,3,0,3,6,Moderate,NaN,NaN,NaN,NaN
2017-11-29 08:00:00,1.0,mist,-0.280000,0,0,3,3,Bad,NaN,NaN,NaN,vandalism
2017-11-29 08:00:00,1.0,mist,-0.280000,0,0,3,3,Bad,NaN,NaN,NaN,vandalism
2017-11-29 08:00:00,1.0,mist,-0.280000,0,0,3,3,Bad,NaN,NaN,NaN,vandalism
2017-11-29 08:00:00,1.0,mist,-0.280000,0,0,3,3,Bad,NaN,NaN,NaN,vandalism
2017-11-29 08:00:00,1.0,mist,-0.280000,0,0,3,3,Bad,NaN,NaN,NaN,vandalism
2017-11-29 08:00:00,1.0,mist,-0.280000,0,0,3,3,Bad,NaN,NaN,NaN,vandalism
2017-11-29 09:00:00,1.0,sky is clear,-0.390000,3,0,3,6,Moderate,NaN,NaN,NaN,NaN
2017-11-29 10:00:00,1.0,sky is clear,-1.190000,3,0,3,6,Moderate,NaN,NaN,NaN,NaN
2017-11-29 11:00:00,2.0,sky is clear,-1.590000,3,0,3,6,Moderate,NaN,NaN,NaN,NaN
2017-11-29 12:00:00,2.0,sky is clear,-1.590000,3,0,3,6,Moderate,NaN,NaN,NaN,assault
2017-11-29 12:00:00,2.0,sky is clear,-1.590000,3,0,3,6,Moderate,NaN,NaN,NaN,assault
2017-11-29 12:00:00,2.0,sky is clear,-1.590000,3,0,3,6,Moderate,NaN,NaN,NaN,assault
2017-11-29 13:00:00,2.0,sky is clear,-1.090000,3,0,3,6,Moderate,NaN,NaN,NaN,NaN
2017-11-29 14:00:00,7.0,broken clouds,0.220000,2,0,2,4,Bad,NaN,NaN,NaN,NaN
2017-11-29 15:00:00,2.0,broken clouds,0.620000,2,0,3,5,Bad,NaN,NaN,NaN,NaN
2017-11-29 16:00:00,2.0,sky is clear,1.920000,3,0,3,6,Moderate,NaN,NaN,NaN,NaN
2017-11-29 17:00:00,1.0,sky is clear,3.610000,3,0,3,6,Moderate,NaN,NaN,NaN,assault
2017-11-29 18:00:00,3.0,sky is clear,10.010000,3,2,3,8,Good,NaN,NaN,NaN,domestic
2017-11-29 19:00:00,4.0,sky is clear,13.570000,3,2,2,7,Moderate,NaN,NaN,NaN,NaN
2017-11-29 20:00:00,3.0,broken clouds,16.410000,2,2,3,7,Moderate,NaN,NaN,NaN,NaN
2017-11-29 21:00:00,6.0,sky is clear,17.550000,3,2,2,7,Moderate,NaN,NaN,NaN,assault
2017-11-29 21:00:00,6.0,sky is clear,17.550000,3,2,2,7,Moderate,NaN,NaN,NaN,domestic
2017-11-29 22:00:00,3.0,sky is clear,16.560000,3,2,3,8,Good,NaN,NaN,NaN,NaN
2017-11-29 23:00:00,1.0,haze,16.020000,2,2,3,7,Moderate,NaN,NaN,NaN,domestic
2017-11-29 23:00:00,1.0,haze,16.020000,2,2,3,7,Moderate,NaN,NaN,NaN,assault
2017-11-30 00:00:00,3.0,sky is clear,12.030000,3,2,3,8,Good,NaN,NaN,NaN,assault

In [400]:
test = test.drop(test.columns[[8]], axis=1)

In [401]:
test.head()

,Wind Speed,Description_x,Celcius,DescRate,TempRate,WindRate,Overall,Weather,Game Day,Domestic,Description_y
2012-10-01 13:00:00,4.0,light rain,11.460000,0,2,2,4,Bad,NaN,NaN,NaN
2012-10-01 14:00:00,4.0,broken clouds,11.457306,2,2,2,6,Moderate,NaN,NaN,NaN
2012-10-01 15:00:00,3.0,broken clouds,11.449918,2,2,3,7,Moderate,NaN,NaN,NaN
2012-10-01 16:00:00,3.0,broken clouds,11.442530,2,2,3,7,Moderate,NaN,NaN,NaN
2012-10-01 17:00:00,3.0,broken clouds,11.435142,2,2,3,7,Moderate,NaN,NaN,NaN

In [402]:
domtest = test

In [403]:
domtest = domtest.drop(domtest.columns[[0, 1, 2, 3, 4, 5, 8]], axis=1)

In [404]:
domtest = domtest.dropna(axis=0, how='any')

In [405]:
domtest

                     Overall   Weather Domestic Description_y
2013-01-02 01:00:00        5       Bad      NBA       assault
2013-01-03 21:00:00        6  Moderate      NBA       assault
2013-01-03 22:00:00        6  Moderate      NBA      domestic
2013-01-04 01:00:00        6  Moderate      NBA      domestic
2013-01-04 03:00:00        6  Moderate      NBA       assault
2013-01-04 03:00:00        6  Moderate      NBA      domestic
2013-01-06 01:00:00        6  Moderate      NBA       assault
2013-01-06 01:00:00        6  Moderate      NBA       assault
2013-01-06 02:00:00        6  Moderate      NBA      domestic
2013-01-06 02:00:00        6  Moderate      NBA       assault
2013-01-06 22:00:00        6  Moderate      NBA     vandalism
2013-01-06 22:00:00        6  Moderate      NBA     vandalism
2013-01-06 22:00:00        6  Moderate      NBA     vandalism
2013-01-06 22:00:00        6  Moderate      NBA     vandalism
2013-01-06 22:00:00        6  Moderate      NBA     vandalism
2013-01-06 22:00:00        6  Moderate      NBA     vandalism
2013-01-07 00:00:00        6  Moderate      NBA       assault
2013-01-09 19:00:00        6  Moderate      NBA       assault
2013-01-09 19:00:00        6  Moderate      NBA       assault
2013-01-09 19:00:00        6  Moderate      NBA      domestic
2013-01-09 22:00:00        6  Moderate      NBA       assault
2013-01-10 03:00:00        6  Moderate      NBA       assault
2013-01-11 21:00:00        5       Bad      NBA      domestic
2013-01-12 00:00:00        5       Bad      NBA      domestic
2013-01-12 00:00:00        5       Bad      NBA       assault
2013-01-12 01:00:00        5       Bad      NBA       assault
2013-01-12 02:00:00        5       Bad      NBA       assault
2013-01-12 02:00:00        5       Bad      NBA      domestic
2013-01-12 23:00:00        5       Bad      NFL       assault
2013-01-12 23:00:00        5       Bad      NFL       assault
...                      ...       ...      ...           ...
2017-04-07 03:00:00        8      Good      NBA      domestic
2017-04-07 18:00:00        8      Good      NBA       assault
2017-04-07 18:00:00        8      Good      NBA       assault
2017-04-07 18:00:00        8      Good      NBA      domestic
2017-04-07 18:00:00        8      Good      NBA      domestic
2017-04-07 18:00:00        8      Good      NBA       assault
2017-04-07 18:00:00        8      Good      NBA       assault
2017-04-07 21:00:00        8      Good      NBA       assault
2017-04-07 22:00:00        8      Good      NBA      domestic
2017-04-07 22:00:00        8      Good      NBA       assault
2017-04-07 22:00:00        8      Good      NBA       assault
2017-04-07 23:00:00        8      Good      NBA     vandalism
2017-04-07 23:00:00        8      Good      NBA     vandalism
2017-04-07 23:00:00        8      Good      NBA     vandalism
2017-04-07 23:00:00        8      Good      NBA     vandalism
2017-04-07 23:00:00        8      Good      NBA     vandalism
2017-04-07 23:00:00        8      Good      NBA     vandalism
2017-04-08 01:00:00        8      Good      NBA      domestic
2017-04-08 01:00:00        8      Good      NBA       assault
2017-04-08 02:00:00        8      Good      NBA       assault
2017-04-08 09:00:00        8      Good      NBA       assault
2017-04-10 03:00:00        5       Bad      NBA      domestic
2017-04-10 03:00:00        5       Bad      NBA      domestic
2017-04-11 22:00:00        7  Moderate      NBA      domestic
2017-04-12 20:00:00        8      Good      NBA      domestic
2017-04-12 20:00:00        8      Good      NBA       assault
2017-04-12 21:00:00        8      Good      NBA       assault
2017-04-12 23:00:00        8      Good      NBA      domestic
2017-04-13 00:00:00        8      Good      NBA       assault
2017-04-13 02:00:00        8      Good      NBA      domestic

[3573 rows x 4 columns]

Only interested in game days.

In [406]:
test = test.drop(test.columns[[9]], axis = 1)

In [407]:
test = test.dropna(axis=0, how='any')

In [408]:
test

,Wind Speed,Description_x,Celcius,DescRate,TempRate,WindRate,Overall,Weather,Game Day,Description_y
2013-01-03 14:00:00,3.0,few clouds,-11.0700,3,0,3,6,Moderate,NBA,assault
2013-01-03 21:00:00,0.0,scattered clouds,-1.0500,3,0,3,6,Moderate,NBA,assault
2013-01-03 22:00:00,2.0,scattered clouds,-0.6900,3,0,3,6,Moderate,NBA,domestic
2013-01-04 01:00:00,2.0,few clouds,-5.9200,3,0,3,6,Moderate,NBA,domestic
2013-01-06 16:00:00,0.0,sky is clear,-1.9900,3,0,3,6,Moderate,NBA,domestic
2013-01-06 22:00:00,3.0,few clouds,3.0800,3,0,3,6,Moderate,NBA,vandalism
2013-01-06 22:00:00,3.0,few clouds,3.0800,3,0,3,6,Moderate,NBA,vandalism
2013-01-06 22:00:00,3.0,few clouds,3.0800,3,0,3,6,Moderate,NBA,vandalism
2013-01-06 22:00:00,3.0,few clouds,3.0800,3,0,3,6,Moderate,NBA,vandalism
2013-01-06 22:00:00,3.0,few clouds,3.0800,3,0,3,6,Moderate,NBA,vandalism
2013-01-06 22:00:00,3.0,few clouds,3.0800,3,0,3,6,Moderate,NBA,vandalism
2013-01-07 00:00:00,2.0,few clouds,-0.8500,3,0,3,6,Moderate,NBA,assault
2013-01-09 13:00:00,3.0,scattered clouds,1.9000,3,0,3,6,Moderate,NBA,assault
2013-01-09 19:00:00,8.0,broken clouds,10.5100,2,2,2,6,Moderate,NBA,assault
2013-01-09 19:00:00,8.0,broken clouds,10.5100,2,2,2,6,Moderate,NBA,assault
2013-01-09 19:00:00,8.0,broken clouds,10.5100,2,2,2,6,Moderate,NBA,domestic
2013-01-09 22:00:00,4.0,broken clouds,10.1500,2,2,2,6,Moderate,NBA,assault
2013-01-10 03:00:00,0.0,few clouds,1.0615,3,0,3,6,Moderate,NBA,assault
2013-01-11 17:00:00,2.0,broken clouds,3.7100,2,0,3,5,Bad,NBA,vandalism
2013-01-11 17:00:00,2.0,broken clouds,3.7100,2,0,3,5,Bad,NBA,vandalism
2013-01-11 17:00:00,2.0,broken clouds,3.7100,2,0,3,5,Bad,NBA,vandalism
2013-01-11 17:00:00,2.0,broken clouds,3.7100,2,0,3,5,Bad,NBA,vandalism
2013-01-11 17:00:00,2.0,broken clouds,3.7100,2,0,3,5,Bad,NBA,vandalism
2013-01-11 17:00:00,2.0,broken clouds,3.7100,2,0,3,5,Bad,NBA,vandalism
2013-01-11 21:00:00,0.0,overcast clouds,3.7900,2,0,3,5,Bad,NBA,domestic
2013-01-12 00:00:00,1.0,broken clouds,2.0000,2,0,3,5,Bad,NBA,domestic
2013-01-12 00:00:00,1.0,broken clouds,2.0000,2,0,3,5,Bad,NBA,assault
2013-01-12 20:00:00,8.0,mist,-1.8900,0,0,2,2,Bad,NFL,vandalism
2013-01-12 20:00:00,8.0,mist,-1.8900,0,0,2,2,Bad,NFL,vandalism
2013-01-12 20:00:00,8.0,mist,-1.8900,0,0,2,2,Bad,NFL,vandalism
...,...,...,...,...,...,...,...,...,...,...
2017-04-07 23:00:00,3.0,broken clouds,23.5000,2,3,3,8,Good,NBA,vandalism
2017-04-07 23:00:00,3.0,broken clouds,23.5000,2,3,3,8,Good,NBA,vandalism
2017-04-08 01:00:00,8.0,sky is clear,22.8400,3,3,2,8,Good,NBA,domestic
2017-04-08 01:00:00,8.0,sky is clear,22.8400,3,3,2,8,Good,NBA,assault
2017-04-08 02:00:00,2.0,overcast clouds,19.4100,2,3,3,8,Good,NBA,assault
2017-04-09 14:00:00,5.0,few clouds,8.8400,3,0,2,5,Bad,NBA,domestic
2017-04-10 03:00:00,8.0,few clouds,6.5000,3,0,2,5,Bad,NBA,domestic
2017-04-10 03:00:00,8.0,few clouds,6.5000,3,0,2,5,Bad,NBA,domestic
2017-04-11 18:00:00,7.0,broken clouds,16.5800,2,2,2,6,Moderate,NBA,assault
2017-04-11 19:00:00,7.0,haze,18.1500,2,2,2,6,Moderate,NBA,domestic
2017-04-11 19:00:00,7.0,haze,18.1500,2,2,2,6,Moderate,NBA,assault
2017-04-11 22:00:00,10.0,broken clouds,20.2800,2,3,2,7,Moderate,NBA,domestic
2017-04-12 18:00:00,4.0,scattered clouds,19.1400,3,3,2,8,Good,NBA,vandalism
2017-04-12 18:00:00,4.0,scattered clouds,19.1400,3,3,2,8,Good,NBA,vandalism
2017-04-12 18:00:00,4.0,scattered clouds,19.1400,3,3,2,8,Good,NBA,vandalism
2017-04-12 18:00:00,4.0,scattered clouds,19.1400,3,3,2,8,Good,NBA,vandalism
2017-04-12 18:00:00,4.0,scattered clouds,19.1400,3,3,2,8,Good,NBA,vandalism
2017-04-12 18:00:00,4.0,scattered clouds,19.1400,3,3,2,8,Good,NBA,vandalism
2017-04-12 18:00:00,4.0,scattered clouds,19.1400,3,3,2,8,Good,NBA,vandalism
2017-04-12 18:00:00,4.0,scattered clouds,19.1400,3,3,2,8,Good,NBA,vandalism
2017-04-12 18:00:00,4.0,scattered clouds,19.1400,3,3,2,8,Good,NBA,vandalism
2017-04-12 18:00:00,4.0,scattered clouds,19.1400,3,3,2,8,Good,NBA,vandalism
2017-04-12 18:00:00,4.0,scattered clouds,19.1400,3,3,2,8,Good,NBA,vandalism
2017-04-12 18:00:00,4.0,scattered clouds,19.1400,3,3,2,8,Good,NBA,vandalism
2017-04-12 19:00:00,4.0,few clouds,20.2800,3,3,2,8,Good,NBA,assault
2017-04-12 20:00:00,4.0,few clouds,21.5800,3,3,2,8,Good,NBA,domestic
2017-04-12 20:00:00,4.0,few clouds,21.5800,3,3,2,8,Good,NBA,assault
2017-04-12 21:00:00,4.0,few clouds,22.1300,3,3,2,8,Good,NBA,assault
2017-04-12 23:00:00,6.0,few clouds,23.0000,3,3,2,8,Good,NBA,domestic
2017-04-13 00:00:00,6.0,few clouds,22.5800,3,3,2,8,Good,NBA,assault

In [409]:
test.index.name = 'Date'

In [410]:
test.head()

,Wind Speed,Description_x,Celcius,DescRate,TempRate,WindRate,Overall,Weather,Game Day,Description_y
Date,,,,,,,,,,
2013-01-03 14:00:00,3.0,few clouds,-11.07,3,0,3,6,Moderate,NBA,assault
2013-01-03 21:00:00,0.0,scattered clouds,-1.05,3,0,3,6,Moderate,NBA,assault
2013-01-03 22:00:00,2.0,scattered clouds,-0.69,3,0,3,6,Moderate,NBA,domestic
2013-01-04 01:00:00,2.0,few clouds,-5.92,3,0,3,6,Moderate,NBA,domestic
2013-01-06 16:00:00,0.0,sky is clear,-1.99,3,0,3,6,Moderate,NBA,domestic

In [411]:
test.to_csv('../../data/prep/denWea_prep.csv')

In [412]:
domtest.index.name = 'Date'

In [413]:
domtest.head()

                     Overall   Weather Domestic Description_y
Date
2013-01-02 01:00:00        5       Bad      NBA       assault
2013-01-03 21:00:00        6  Moderate      NBA       assault
2013-01-03 22:00:00        6  Moderate      NBA      domestic
2013-01-04 01:00:00        6  Moderate      NBA      domestic
2013-01-04 03:00:00        6  Moderate      NBA       assault

In [414]:
domtest.to_csv('../../data/prep/denWea_dom_prep.csv')